### PR TITLE
Support for resumed downloads (enabled by default)

### LINKED ISSUE #24: Download resumption
I was downloading the 150GB dataset for https://www.kaggle.com/c/imagenet-object-localization-challenge/data using this CLI, but unfortunately the connection broke after about 100GB and the tool would not pick up where it stopped when I called it again. Luckily https://github.com/floydwch/kaggle-cli was able to resume the download, so I didn't have to download it over again. However, it would be nice if this tool was able to automatically resume the download if it got interrupted.

### PR DESCRIPTION
**Pull request by csachs**
Reopen of #328 (can't change the target branch).
( Should fix #24 , #310 , #316 )

### CODE REVIEW

**Comment by DapengFeng** [comment]
Thanks for your work. But I am still confused about how to resume the download process when failing in the following command
```
kaggle competitions download -c imagenet-object-localization-challenge
```

**Comment by tmijieux** [comment]
> Thanks for your work. But I am still confused about how to resume the download process when failing in the following command
> 
> ```
> kaggle competitions download -c imagenet-object-localization-challenge
> ```

I did not test it yet, but seeing the code i would say that you just have to relaunch the same command,
it automatically detects if the file exists and will send appropriate headers according to existing file size to start again where it stopped.

**Comment by tmijieux** [comment]
@csachs maybe you could also change the return of the `download_needed` to True when
- "date check" is good( local file was created after remote 'Last-Modified') 
- BUT  local file size is smaller than remote file size (which is detection that the file download was interrupted)

exactly like what you did at the beginning of the `download_file` function

**Comment by Philmod** [comment]
Thanks @csachs and @tmijieux, I'm going to implement this solution.

The source of code is internal, and is copied here, that's why I cannot merge this PR directly.

**Comment by Philmod** [comment]
https://github.com/Kaggle/kaggle-api/releases/tag/1.5.14

**Pull request closed without merging**
