### PR TITLE
Turn internet on by default

### PR DESCRIPTION
**Pull request by Philmod**
b/135010857

### CODE REVIEW

**Comment by alexisbcook** [comment]
We need to make sure that this change does not automatically toggle internet 'on' in metadata files for learn exercises. @jplotts 

here's the relevant file: https://github.com/Kaggle/learntools/blob/master/notebooks/prepare_push.py

**Comment by jplotts** [comment]
@alexisbcook - Forks will still inherit the settings of the parent, which means we only need to worry about the published exercises.  Learntools already seems to set `enable_internet` to false when not in development mode: https://github.com/Kaggle/learntools/blob/63d8a940b69f8b89739a3910a4078c577e749764/notebooks/nb_utils/track_metadata.py#L215

Is that enough?

**Comment by alexisbcook** [comment]
yes - looks good to me. thanks, jim!

**Comment by jplotts** [comment]
@alexisbcook - thanks for verifying!  Please keep an eye out and LMK if anything looks funny.  I don't know much about learntools.

**Pull request merged**
