### PR TITLE
Update Readme - use pip show command

### PR DESCRIPTION
**Pull request by rlneumiller**
Use pip show command to view installed location of kaggle package

### CODE REVIEW

**Comment by rlneumiller** [comment]
Let's try that again

**Review by stevemessick — APPROVED** [review]

**Review by stevemessick — COMMENTED** [review]
Actually, using `pip show` does not print the location that needs to be added to the PATH. So I don't think we want to make this change.

**Comment by rlneumiller** [comment]
I've updated the patch to address the implication that to find kaggle the user needs to uninstall it first.

**Comment by stevemessick** [comment]
Thanks for the update! I'll review it soon.

**Review by stevemessick — APPROVED** [review]

**Comment by anfal-abubakr46** [comment]
Hello, I am a beginner and I don't know where to start

**Pull request merged**
