### PR TITLE
Support for resumable downloads

### LINKED ISSUE #24: Download resumption
I was downloading the 150GB dataset for https://www.kaggle.com/c/imagenet-object-localization-challenge/data using this CLI, but unfortunately the connection broke after about 100GB and the tool would not pick up where it stopped when I called it again. Luckily https://github.com/floydwch/kaggle-cli was able to resume the download, so I didn't have to download it over again. However, it would be nice if this tool was able to automatically resume the download if it got interrupted.

### PR DESCRIPTION
**Pull request by csachs**
Should fix #24 , #310 , #316 
Since I started downloading a large dataset, and asked myself the same questions as many other users, I looked into this.
Attached is support for resuming download operations. While I'm no expert on the API, a bit of debugging shows that the storage location of the data (Google Cloud Storage) allows the necessary range requests. Sadly, the autogenerated Swagger API functions don't allow directly passing the necessary header values. Assuming the the current set of redirects (maybe the team can comment if that assumption holds true?), however a simple workaround seems to just create a new HTTP request to the appropriate URL if resuming is desired, with the appropriate range header. To aid identifying incomplete files, the file's modification time is set to the last modification minus one second according to the HTTP headers (and set to the right time once the file is complete), hence the existing `download_needed` can spot incomplete files.

I'm new to using the Kaggle CLI, so ideally someone accustomed with the workflows could check if the resuming support breaks anything else (I've so far tried it with competition data only, where it successfully resumed them, leading to bit-identical files).

### CODE REVIEW

**Comment by vaibhawc** [comment]
We are building reusable rockets but this pr is still open.

**Comment by jdddog** [comment]
> We are building reusable rockets but this pr is still open.

Aside from user frustration, surely the wasted Google Cloud storage egress costs, which would be pretty large considering the datasets, would justify enough engineer time to review the pull request and merge it.

**Comment by ccl-private** [comment]
imagenet-object-localization-challenge.zip: Skipping, found more recently modified local copy (use --force to force download)

**Comment by ccl-private** [comment]
I try to resum download， but meet： imagenet-object-localization-challenge.zip: Skipping, found more recently modified local copy (use --force to force download)

**Comment by csachs** [comment]
@ccl-private did you download the unfinished part with the original client, and then got the resumable patch from this PR? In that case this may happen … 
Theoretically, you should be able to workaround this by manually setting the mtime of your unfinished file to some date earlier than the file's regular mtime on the server (so some dummy value like 1970-01-01 should be fine…)

**Comment by ccl-private** [comment]
@csachs I download the unfinished part with  this PR， install using python setup install.

**Comment by ccl-private** [comment]
oh！I forget checkout git branch to resumable.

**Comment by csachs** [comment]
@ccl-private Does it work now?

**Comment by ccl-private** [comment]
yes，it works. thank you～

**Comment by taehyunzzz** [comment]
@csachs Really appreciate you sharing your work :)

**Comment by kamarain** [comment]
Since which version is download resume available? I installed the most recent with Conda (Kaggle API 1.5.12), but it failed to continue downloading ImageNet data, complained about the version and force just tries to download whole file again. Am I missing something here since I don't see resume download working?

**Comment by jplotts** [comment]
Hi @kamarain - this PR has not been merged into master, so you would need to use this person's branch directly.  Kaggle is not currently merging PRs unless they are critical fixes because we are revamping the infrastructure behind the API.

**Comment by dylanhogg** [comment]
It would be great if someone with write access could review this PR that has been open for over 1 year.

Who is able to merge or at least provide feedback as to why it can't be merged?

**Comment by chAwater** [comment]
- also fix #341

**Pull request closed without merging**
