### PR TITLE
Adding unzip, toml, and java to install-deps.

### PR DESCRIPTION
**Pull request by mgallifrey**
Note that unzip must be installed first, as it's used to install autogen.

Fixes https://github.com/Kaggle/kaggle-api/issues/599.

### CODE REVIEW

**Comment by stevemessick** [comment]
I need to verify that this won't cause problems for Kaggle's internal development environment. I'm a bit new to Docker so I'll have to install this in a test env and make sure everything still works. I'll get to it, but not right away. Anyway, thanks for the PR!

**Review by Knowledge84 — APPROVED** [review]

**Review by stevemessick — APPROVED** [review]
Thanks!

**Pull request merged**
